version: '3'

services:
  ddsr-api:
    build: ./DDSR-api
    ports:
      - 5000:5000
    volumes:
      - ./DDSR-api:/ddsr-api
    depends_on:
      - mongodb 
 
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ddsr-mongo:/usr/data/db
    ports:
      - 27017:27017

volumes:
  ddsr-mongo:
    external: false